import crypto from 'node:crypto';
import { isAuthenticated } from './_admin-auth.js';

const GOOGLE_TOKEN_URL='https://oauth2.googleapis.com/token';
const CALENDAR_API='https://www.googleapis.com/calendar/v3';
const TIME_ZONE='Europe/Zurich';
function base64Url(v){return Buffer.from(v).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function parseServiceAccount(raw){const a=JSON.parse(raw);if(!a.client_email||!a.private_key)throw new Error('SERVICE_ACCOUNT_INVALID');a.private_key=a.private_key.replace(/\\n/g,'\n').replace(/\\r/g,'\r');return a}
function getServiceAccount(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(raw)return parseServiceAccount(raw.trim());const b=process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64;if(b)return parseServiceAccount(Buffer.from(b.trim(),'base64').toString('utf8'));throw new Error('SERVICE_ACCOUNT_MISSING')}
async function token(){const a=getServiceAccount(),now=Math.floor(Date.now()/1000),h=base64Url(JSON.stringify({alg:'RS256',typ:'JWT'})),c=base64Url(JSON.stringify({iss:a.client_email,scope:'https://www.googleapis.com/auth/calendar',aud:GOOGLE_TOKEN_URL,iat:now,exp:now+3600})),u=`${h}.${c}`,s=crypto.createSign('RSA-SHA256');s.update(u);s.end();const sig=s.sign(a.private_key,'base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');const r=await fetch(GOOGLE_TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${u}.${sig}`})}),d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||'AUTH_FAILED');return d.access_token}
function calendarId(){const id=process.env.GOOGLE_CALENDAR_ID;if(!id)throw new Error('CALENDAR_ID_MISSING');return id}
function eventUrl(id){return `${CALENDAR_API}/calendars/${encodeURIComponent(calendarId())}/events/${encodeURIComponent(id)}`}
async function hasConflict(access,id,start,end){const p=new URLSearchParams({timeMin:new Date(start).toISOString(),timeMax:new Date(end).toISOString(),singleEvents:'true',orderBy:'startTime',maxResults:'25'});const r=await fetch(`${CALENDAR_API}/calendars/${encodeURIComponent(calendarId())}/events?${p}`,{headers:{Authorization:`Bearer ${access}`}});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'CALENDAR_CONFLICT_CHECK_FAILED');return (d.items||[]).some(e=>e.status!=='cancelled'&&e.id!==id)}
export default async function handler(req,res){if(!['PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','PATCH, DELETE');return res.status(405).json({error:'Méthode non autorisée.'})}if(!isAuthenticated(req))return res.status(401).json({error:'Non autorisé.'});try{const id=String(req.query?.id||req.body?.id||'').trim();if(!id)return res.status(400).json({error:'Rendez-vous manquant.'});const access=await token();if(req.method==='DELETE'){const r=await fetch(eventUrl(id),{method:'DELETE',headers:{Authorization:`Bearer ${access}`}});if(!r.ok&&r.status!==204){let d={};try{d=await r.json()}catch{}throw new Error(d.error?.message||'CALENDAR_DELETE_FAILED')}return res.status(200).json({ok:true})}
const {start,end}=req.body||{};if(!start||!end||isNaN(Date.parse(start))||isNaN(Date.parse(end))||Date.parse(end)<=Date.parse(start))return res.status(400).json({error:'Date ou heure invalide.'});if(await hasConflict(access,id,start,end))return res.status(409).json({error:'Ce créneau est déjà occupé. Choisissez une autre heure.',code:'SLOT_UNAVAILABLE'});const r=await fetch(eventUrl(id),{method:'PATCH',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({start:{dateTime:start,timeZone:TIME_ZONE},end:{dateTime:end,timeZone:TIME_ZONE}})}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||'CALENDAR_UPDATE_FAILED');return res.status(200).json({ok:true,event:{id:d.id,start:d.start?.dateTime,end:d.end?.dateTime}})}catch(error){console.error('Admin event mutation:',error);return res.status(500).json({error:req.method==='DELETE'?'Impossible d’annuler le rendez-vous.':'Impossible de modifier le rendez-vous.',diagnostic:error?.message||'Erreur inconnue.'})}}
